### ISSUE TITLE
[ELE-1501] [ELE-1502] temp tables break with expression column

### ISSUE THREAD

**Issue by ofek1weiss** [elementary-data/elementary#1062]
when a test is defined on a column that is an expression:
```
columns:
  - name: col_a || col_b
    tests:
       ....
```
the temp table creation breaks :(

<sub>[ELE-1502](https://linear.app/elementary/issue/ELE-1502/temp-tables-break-with-expression-column)</sub>
