### ISSUE TITLE
Add functionality for group level alerting

### ISSUE THREAD

**Issue by jelstongreen** [elementary-data/elementary#1111]
**Is your feature request related to a problem? Please describe.**
It is tedious to have to list owners for each model individually when entire directories of models often belong to the same people. 

**Describe the solution you'd like**
With groups you can assign ownership like: 
```
version: 2
groups:
  - name: my_group
    owner:
      name: My Team
      slack: my-team
      members: ['a_user@mycompany.com','b_user@mycompany.com]
      subscribers: ['c_user@mycompany.com']
```

It would be amazing if we could parse the group level yml to determine who to tag in slack alerting which removes the requirement to add model level alert configuration. 

**Describe alternatives you've considered**
None

**Additional context**

**Would you be willing to contribute this feature?**
Yes!
