### ISSUE TITLE
Force alerts or override disable_warn_alerts: true for warnings 

### ISSUE THREAD

**Issue by jennaallen** [elementary-data/elementary#1180]
**Is your feature request related to a problem? Please describe.**
I have a handful of tests with severity of warning, that I'd like to get alerts for when `disable_warn_alerts: true`

**Describe the solution you'd like**
Maybe some type of override at the test level.
```
version: 2
models:
  - name: large_table
    columns:
      - name: slightly_unreliable_column
        tests:
          - unique:
              severity: warn
              < something I can put here to override disable_warn_alerts: true >
```

**Describe alternatives you've considered**
I could turn the tests to error instead of warn, but one particular test blocks our entire CI pipeline when it is failing and I can't merge any new PRs, so I want to leave as a warning, but I still need an alert to know that it's failing.

**Additional context**
Original slack question https://elementary-community.slack.com/archives/C02CTC89LAX/p1695761610970439

**Would you be willing to contribute this feature?**
Sure, that could be fun!
