### ISSUE TITLE
Custom test name does not show in report html file

### ISSUE THREAD

**Issue by yatsky** [elementary-data/elementary#1224]
**Describe the bug**
The `Test name` column in HTML file does not reflect custom test name set in the yaml config.
**To Reproduce**

Given the following yaml config
```yaml
version: 2

sources:
    - name: example_schema
      tables:
        - name: example_table
          meta:
            elementary:
              timestamp_column: "timestamp_column"
          tests:
            - elementary.volume_anomalies:
                name: "example table is stable"
                where_expression: "timestamp_column between dateadd(day, -10, current_date()) and current_date()"
                anomaly_sensitivity: 2
                backfill_days: 7
                days_back: 10
```
Run `dbt test` in the console and we get correct output.
> 08:23:59  1 of 3 START test example table is stable ........................ [RUN]

However, in the final HTML report, the test name is not correctly reflected.

![image](https://github.com/elementary-data/elementary/assets/9735384/6a200ac5-c374-43ef-bbbd-87a4ddbbf0ba)

**Expected behavior**
The custom test name should be relected in the `Test name` column in the final HTML file.

**Screenshots**
Attached above.

**Environment (please complete the following information):**

- edr Version: 0.11.0
- dbt package Version: 0.11.1

**Additional context**
See original Slack conversation: https://elementary-community.slack.com/archives/C02CTC89LAX/p1696829659325819
