### ISSUE TITLE
Add support for tag declarations to the config / meta per model

### ISSUE THREAD

**Issue by eraliod** [elementary-data/elementary#1225]
**Is your feature request related to a problem? Please describe.**
would help clean up the configuration and avoid repetitive code if we can configure tags for all tests in a model / source

**Describe the solution you'd like**
```
sources:
  - name: agent
      meta:
        elementary:
          tags: ["sources"]
     tests:
       - elementary.schema_changes:
       - elementary.volume_anomalies:
```
```
models:
  - name: agent
      config:
        elementary:
          tags: ["marts"]
     tests:
       - elementary.schema_changes:
       - elementary.volume_anomalies:
```

**Describe alternatives you've considered**
tags has to be repeated under each test
```
sources:
  - name: agent
     tests:
       - elementary.schema_changes:
           tags: ["sources"]
       - elementary.volume_anomalies:
           tags: ["sources"]
```

**Additional context**
I thought setting tags in the meta / config would work and tested it on 0.11.1 but it does not appear to work when I try to run `dbt test --select tag:sources`. Inline tags declarations do work as intended.

**Would you be willing to contribute this feature?**
Not able to contribute at this time
