### ISSUE TITLE
Freshness anomaly detection test false positive?

### ISSUE THREAD

**Issue by gbatiz** [elementary-data/elementary#1227]
Path: /guides/anomaly-detection-tests/freshness-anomalies

I am not sure if this is a bug, or the docs aren't clear to me.
When implementing a test, I always try to make it fail, before trusting it.

I am trying to fail the below freshness anomaly test:

```yml
version: 2
models:

- name: stg_erp_contracts

  config:
    alias: erp_contracts
    schema: staging_events
    elementary:
      timestamp_column: _META_LOADED_AT
  tests:
    - elementary.freshness_anomalies:
        severity: warn
        anomaly_sensitivity: 0.00001
        backfill_days: 2
        days_back: 28
        anomaly_direction: both
        time_bucket:
          period: day
          count: 1
        seasonality: day_of_week
        min_training_set_size: 14
```

And I am getting the below result.
**I don't understand why this test doesn't fail if every single point in time is a failure.**

![Screenshot from 2023-10-13 13-10-11](https://github.com/elementary-data/elementary/assets/39667935/aaf0c66f-e5f6-40cd-a1a2-56eed53b840d)
