### ISSUE TITLE
ERROR — Could not generate the report - Error: Failed to run dbt command

### ISSUE THREAD

**Issue by KarthikRajashekaran** [elementary-data/elementary#1269]
**Describe the bug**
When below command is run 

`edr send-report --s3-bucket-name abc --bucket-file-path /edr/index.html --project-dir /opt/airflow/dbt-dir/ --profiles-dir /opt/airflow/dbt-dir/ -c /mnt/working-dir -st *** -ch elem_alerts
`
It throws below error

```
[2023-11-07, 21:10:29 EST] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'edr send-report --s3-bucket-name abc --bucket-file-path /edr/index.html --project-dir /opt/airflow/dbt-dir/ --profiles-dir /opt/airflow/dbt-dir/ -c /mnt/working-dir -st *** -ch elem_alerts']
[2023-11-07, 21:10:29 EST] {subprocess.py:85} INFO - Output:
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO -     ________                          __
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO -    / ____/ /__  ____ ___  ___  ____  / /_____ ________  __
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO -   / __/ / / _ \/ __ `__ \/ _ \/ __ \/ __/ __ `/ ___/ / / /
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO -  / /___/ /  __/ / / / / /  __/ / / / /_/ /_/ / /  / /_/ /
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO - /_____/_/\___/_/ /_/ /_/\___/_/ /_/\__/\__,_/_/   \__, /
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO -                                                  /____/
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO - 
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO - Any feedback and suggestions are welcomed! join our community here - https://bit.ly/slack-elementary
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO - 
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:32 — INFO — Running with edr=0.12.0
[2023-11-07, 21:10:32 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:32 — INFO — Running dbt --log-format json deps --project-dir /mnt/working-dir/edr/elementary/monitor/dbt_project --profiles-dir /opt/airflow/dbt-dir/
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Running with dbt=1.7.1
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Updating lock file in file path: /mnt/working-dir/edr/elementary/monitor/dbt_project/package-lock.yml
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Installing dbt-labs/dbt_utils
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Installed from version 0.8.6
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Updated version available: 1.1.1
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Installing elementary-data/elementary
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Installed from version 0.12.0
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Updated version available: 0.12.1
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO —
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - 2023-11-08 02:10:39 — INFO — Updates available for packages: ['dbt-labs/dbt_utils', 'elementary-data/elementary']
[2023-11-07, 21:10:39 EST] {subprocess.py:92} INFO - Update your versions in packages.yml, then run dbt deps
[2023-11-07, 21:11:08 EST] {subprocess.py:92} INFO - 2023-11-08 02:11:08 — INFO — edr (0.12.0) and Elementary's dbt package (0.12.1) are compatible.
[2023-11-07, 21:11:17 EST] {subprocess.py:92} INFO - 2023-11-08 02:11:17 — INFO — Elementary's database and schema: '"DEV.METRICS_elementary"'
[2023-11-07, 21:11:17 EST] {subprocess.py:92} INFO - 2023-11-08 02:11:17 — INFO — Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /mnt/working-dir/edr/elementary/monitor/dbt_project --profiles-dir /opt/airflow/dbt-dir/
[2023-11-07, 21:11:34 EST] {subprocess.py:92} INFO - [31;20m2023-11-08 02:11:34 — ERROR — Could not generate the report - Error: Failed to run dbt command.
[2023-11-07, 21:11:34 EST] {subprocess.py:92} INFO - Please reach out to our community for help with this issue.[0m
[2023-11-07, 21:11:34 EST] {subprocess.py:92} INFO - NoneType: None
[2023-11-07, 21:11:35 EST] {subprocess.py:96} INFO - Command exited with return code 1
[2023-11-07, 21:11:35 EST] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/working-dir/avalara_ds/airflow/operators/dbt_bash.py", line 97, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
```

**Expected behavior**
Should be able to run edr send-report command 
It was running fine before edr version 0.12.0 

I also updated the dbt packages latest on 0.12.1 and run dbt deps and  dbt run --select elementary

**Environment (please complete the following information):**

`edr=0.12.0`
`dbt=1.7.1`

```
packages:
    ## Docs: https://docs.elementary-data.com
    ## Monitor your data quality, operation and performance directly from your dbt project
  - package: elementary-data/elementary
    version: 0.12.1
    ## contains macros that can be (re)used across dbt projects
  - package: dbt-labs/dbt_utils
    version: 1.1.1
    ## helps assert expectations for different dataset characteristics and column values
  - package: calogica/dbt_expectations
    version: 0.10.0
    ## Macros that generate dbt code, and log it to the command line
  - package: dbt-labs/codegen
    version: 0.11.0
```

**Additional context**
