### ISSUE TITLE
avg_percent_anomalous_condition macro should use OR instead of AND condition to correctly calculate is_anomalous when anomaly_direction='both'

### ISSUE THREAD

**Issue by trevdoz** [elementary-data/elementary#1285]
**Describe the bug**
Please checkout the lines in the file referenced below. If anomaly_direction is **both** then this needs to use `or` instead of `and` condition since spike and drop are mutually exclusive

https://github.com/elementary-data/dbt-data-reliability/blob/b234a2f460813d477b87ef464a7350270da0c843/macros/edr/tests/test_utils/get_anomaly_query.sql#L120-L134C17

**To Reproduce**
Create a test that is configured as follows:
```yaml
models:
  - name: this_is_a_model
    tests:
      ignore_small_changes:
        spike_failure_percent_threshold: 2
        drop_failure_percent_threshold: 50
     anomaly_direction: both
```
This test will always result in FALSE for **is_anomalous** column since the case when expression in the macro uses an `and` condition

**Expected behavior**
Expected a test to fail if spike condition is met OR the drop condition is met. BOTH conditions will never be met

**Environment (please complete the following information):**

- dbt package Version: 0.12.1
