### ISSUE TITLE
Add support for column- and test-level tags in the sidebar

### ISSUE THREAD

**Issue by henrik-brodtkorb** [elementary-data/elementary#1375]
**Is your feature request related to a problem? Please describe.**
Currently only model-level tags are shown in the report sidebar. 

**Describe the solution you'd like**
My use case is the ability to give report viewers a filter enabling them to easily filter test results to tests relevant to them. 

For example, with the below configuration, the SEO team can filter for SEO alerts, and paid media can filter for Paid Media alerts. 
```yaml
version: 2

models:
  - name: adobe_analytics_acquisition
    description: marketing performance from adobe analytics
    config:
      elementary:
        timestamp_column: date_day

    tests:
      - elementary.all_columns_anomalies:
          column_anomalies:
            - sum
          tags: ["SEO"]
          where_expression: "marketing_channel = 'Natural Search'"
          
      - elementary.all_columns_anomalies:
          column_anomalies:
            - sum
          tags: ["Paid Media"]
          where_expression: "marketing_channel = 'SEA'"
```

**Describe alternatives you've considered**
I have considered creating separate models for SEO and Paid Media, then using model-level tags. While this works, it will create a lot more models in the project and overhead when testing. 

**Additional context**
https://elementary-community.slack.com/archives/C02CTC89LAX/p1705398003258569

**Would you be willing to contribute this feature?**
Perhaps
