### ISSUE TITLE
"Schema changes from baseline" test - "Auto-generate baseline schema" does not work as expected, is redundant?

### ISSUE THREAD

**Issue by arthurcht** [elementary-data/elementary#1455]
**Describe the gap**
[Current docs](https://docs.elementary-data.com/data-tests/schema-tests/schema-changes-from-baseline)
does not show how test parameters (e.g.  `fail_on_added`) can be added in `sources` .yml configuration.

Instead, option to auto-generate baseline schema using `generate_schema_baseline_test` macro is documented, but does not seem to behave as expected. I ran `dbt run-operation elementary.generate_schema_baseline_test --args '{"include_sources": true, "fail_on_added": true, "enforce_types": true}'`, but test did not fail when a column was added.

**Additional context**
Steps to reproduce unexpected behaviour, in Postgres (using pgAdmin4):

- CREATE source table raw_transactions , then INSERT values
```
CREATE TABLE "dbtSchema_Arthur20240304".raw_transactions
        (
            timestamp timestamp without time zone,
            transaction_id character(4),
            customer_id smallint
        );

INSERT INTO "dbtSchema_Arthur20240304".raw_transactions (timestamp, transaction_id, customer_id)
        VALUES
            ('2024-03-08 04:05:06', NULL, 1),
            ('2024-03-09 04:05:06', '1034', 25),
            ('2024-03-10 03:26:37', '1008', 3)
```

- in `<dbt project directory>/models/schema.yml`, add source table configurations including test `elementary.schema_changes_from_baseline` without parameters
```
version: 2

sources:
  - name: dbtSchema_Arthur20240304
    database: postgres
    schema: dbtSchema_Arthur20240304
    tables:
      - name: raw_transactions
        columns:
          - name: timestamp
            data_type: timestamp without time zone
          - name: transaction_id
            data_type: character
          - name: customer_id
            data_type: smallint
        tests:
          - elementary.schema_changes_from_baseline
```

- run `dbt run-operation elementary.generate_schema_baseline_test --args '{"include_sources": true, "fail_on_added": true, "enforce_types": true}'` _note: instead of BEFORE, running this AFTER `dbt build` leads to same result, i.e. test does not fail when column added_
- run `dbt build` to generate Elementary schema
- run `edr report` to verify `raw_transactions` source table is being monitored and tested for `schema_changes_from_baseline`

- ADD column into `raw_transactions` source table, that is not defined in `schema.yml` - this is **expected to fail test `schema_changes_from_baseline`**
```
ALTER TABLE "dbtSchema_Arthur20240304".raw_transactions
ADD is_paid boolean;
```
- run `dbt build`, then `edr report` - **expected `schema_changes_from_baseline` test failure alert, but test passed**

**Suggested documentation fix**
in [Current docs](https://docs.elementary-data.com/data-tests/schema-tests/schema-changes-from-baseline),

- in code examples "Sources example" and "Models example", show how parameters (e.g. `fail_on_added`) can be added:
```
version: 2

sources:
  - name: dbtSchema_Arthur20240304
    database: postgres
    schema: dbtSchema_Arthur20240304
    tables:
      - name: raw_transactions
        columns:
          - name: timestamp
            data_type: timestamp without time zone
          - name: transaction_id
            data_type: character
          - name: customer_id
            data_type: smallint
        tests:
          - elementary.schema_changes_from_baseline:
              fail_on_added: true
              enforce_types: true
```

- remove section on `Auto-generate baseline schema` --> with test parameter configurations in .yml as shown above, without running `dbt run-operation elementary.generate_schema_baseline_test etc.`, test failed as expected when column was added. So using `generate_schema_baseline_test` macro seems redundant? instead,

- could mention that baseline schema is generated when:
1. test `elementary.schema_changes_from_baseline` (with test parameters, if needed) is configured in .yml
2. `dbt build` is run for the first time with .yml configuration
