### ISSUE TITLE
elementary.schema_changes_from_baseline Test Fails for Certain Source Tables

### ISSUE THREAD

**Issue by ahmedhamidibr** [elementary-data/elementary#1460]
**Describe the bug**
The issue arises when executing  schema_changes_from_baseline test  on source tables, it works for some tables and fails for others . For example:

```yml
sources:
  - name: raw
    tables:
  - name: source_table_one
    columns:
    
      - name: NAME
        data_type: VARCHAR
    
      - name: CREATEDBYID
        data_type: VARCHAR
    
      - name: CREATEDDATE
        data_type: TIMESTAMP_TZ
    
      - name: ID
        data_type: VARCHAR

    tests:
      - elementary.schema_changes_from_baseline

  - name: source_table_two
    columns:
    
      - name: NAME
        data_type: VARCHAR
    
      - name: CREATEDBYID
        data_type: VARCHAR
    
      - name: CREATEDDATE
        data_type: TIMESTAMP_TZ
    
      - name: ID
        data_type: VARCHAR

    tests:
      - elementary.schema_changes_from_baseline
```

Despite the tables sharing the same schema, the test fails for one table while succeeding for another. This inconsistency is observed even though both tables are defined with the same columns and data types in the dbt project's schema configuration. The error am getting is :

```
Compilation Error in test elementary_source_schema_changes_from_baseline_raw_source_table_two_ (models/schema.yml)
  'str object' has no attribute 'database'
  
  > in macro load_relation (macros/adapters/relation.sql)
  > called by macro get_model_baseline_columns (macros/edr/tests/test_configuration/get_model_baseline_columns.sql)
  > called by macro test_schema_changes_from_baseline (macros/edr/tests/test_schema_changes_from_baseline.sql)
  > called by test elementary_source_schema_changes_from_baseline_raw_salesforce_campaignmember_ (models/schema.yml)
```

**To Reproduce**

1. generate columns and their data types for source table 
 `dbt run-operation elementary.generate_schema_baseline_test --args '{"name": "source_table"}'`
2. run schema_changes_from_baseline test on source table
`dbt test --select source:raw.source_table`

**Expected behavior**
The elementary.schema_changes_from_baseline test should run successfully for all source tables, provided that all columns and their respective data types are accurately defined in the table configurations. 

**Environment (please complete the following information):**

- edr Version:  0.14.1, can be found by running `pip show elementary-data`
- dbt package Version:  0.14.1, can be found in `packages.yml` file
