### ISSUE TITLE
elementary column anomalies tests fail on redshift with error 'Relation name is longer than 127 characters'

### ISSUE THREAD

**Issue by MiConnell** [elementary-data/elementary#1498]
**Describe the bug**
elementary `column_anomalies` tests are unable to run on Redshift due to table naming length restrictions

**To Reproduce**

1. add `elementary.column_anomalies` tests to columns in a dbt model that builds in Redshift
```yaml
columns:
      - name: id
        tests:
          - elementary.column_anomalies:
              column_anomalies:
                - null_count
                - missing_count
                - average
        description: ''
        meta:
          hidden: true
```
2. test the model with `dbt test -s my_model`

error occurs:
```bash
Runtime Error in test elementary_column_anomalies_fact_table_null_count__missing_count__average__success_count (models/marts/fact_table.yml)
Relation name '"test_7ffaec620b_elementary_column_anomalies_fact_table_null_count__missing_count__av__metrics__tmp_20240423000522692548"' is longer than 127 characters
```

**Expected behavior**
Tests run successfully and elementary is able to create temp tables

**Environment (please complete the following information):**

- edr Version: N/A
- dbt package Version: 0.14.1

**Additional context**
dbt running in prod redshift
