### ISSUE TITLE
Elementary runs hooks even when everything is disabled.

### ISSUE THREAD

**Issue by lfpll** [elementary-data/elementary#1581]
**Describe the bug**
It's not possible to really disable the elementary hooks, even if you disable all the autoupdates the hook will still run.

**To Reproduce**

Save your `dbt_project.yml` in 

```
vars:
  disable_run_results: true
  disable_freshness_results: true
  disable_tests_results: true
  disable_dbt_artifacts_autoupload: true
  disable_dbt_columns_autoupload:  true
  disable_dbt_invocation_autoupload: true
```

Have the elementary enabled and run, this will still show the on-run-start

The option is running 

```yaml
elementary:
        enable: false
```

The problem with this is that I have to many models and my elementary breaks.

**Expected behavior**
I want to be able to run elementary manually and not run any hooks.

**Environment (please complete the following information):**

- Elementary dbt package version: 1.5.3
- dbt version you're using: 1.6.7
- Data warehouse: Bigquery
- Infrastructure details: Linux containareized python 3.9

** Suggestion **

```yaml
on-run-start:
  - "{{ elementary.on_run_start() if env_var('DISABLE_ELEMENTARY_HOOKS','false') != 'true' else None}}"
on-run-end:
  - "{{ elementary.on_run_end() if env_var('DISABLE_ELEMENTARY_HOOKS','false') != 'true' else None}}"
```

This would solve my problem
