### ISSUE TITLE
 Macro 'dbt_macro__test_event_freshness_anomalies' takes no keyword argument 'training_period'

### ISSUE THREAD

**Issue by annav00** [elementary-data/elementary#1641]
**Describe the bug**
If you specify `training_period` in the `event_freshness_anomalies` test parameters, then the test crashes at the compilation stage with error

```
Compilation Error in test elementary_event_freshness_anomalies_accounts_VALID_TO_DTTM__hour__1__day__7__PROCESSED_DTTM (models/stg_history/schema.yaml)
  macro 'dbt_macro__test_event_freshness_anomalies' takes no keyword argument 'training_period'
```

**To Reproduce**

1. Test parameters:

```
  - elementary.event_freshness_anomalies:
      training_period:
        period: day
        count: 2
      update_timestamp_column: PROCESSED_DTTM
      event_timestamp_column: VALID_FROM_DTTM
```
2. run  dbt test

**Expected behavior**

**Screenshots**
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/98279373-5066-47ee-9db6-3b609084d387">

**Environment (please complete the following information):**

- Elementary dbt package version: 0.15.2
- Data warehouse: snowflake

**Additional context**
The event_freshness_anomalies macro, that it does not have parameter `training_period`.

`{% test event_freshness_anomalies(model, event_timestamp_column, update_timestamp_column, where_expression, anomaly_sensitivity, anomaly_direction, min_training_set_size, time_bucket, days_back, backfill_days, sensitivity, ignore_small_changes, detection_delay, anomaly_exclude_metrics) %}`

**Would you be willing to contribute a fix for this issue?**
Yes, I can fix this problem by adding a training_period parameter to the macro event_freshness_anomalies
