### ISSUE TITLE
Missing max tests in report when defining it together with min tests

### ISSUE THREAD

**Issue by retrry** [elementary-data/elementary#1662]
**Describe the bug**
Missing max tests, when defining tests in `schema.yml`

**To Reproduce**
1. Define tests for model in `schema.yml`

```
  - elementary.column_anomalies:
      column_anomalies:
        - max
        - min
      column_name: "value_column"
      timestamp_column: "measured_at"
      training_period:
        period: month
        count: 1
      time_bucket:
        period: hour
        count: 12
      detection_delay:
        period: hour
        count: 12
      ignore_small_changes:
        spike_failure_percent_threshold: 10
        drop_failure_percent_threshold: 10
```
2. Run `dbt run && dbt test`
3. Run `edr report`

**Expected behavior**
I expect to find `min` and `max` tests in generated report, but I only find `min` tests in the report.

**Screenshots**

**Environment (please complete the following information):**

- Elementary CLI (edr) version: 0,16
- Elementary dbt package version:  0.16
- dbt version you're using: 1.8.4
- Data warehouse: postgres
- Infrastructure details: macOS

**Additional context**
I have defined separate tests in `schema.yml`
```
  - elementary.column_anomalies:
      column_anomalies:
        - average
        - standard_deviation
        - variance
      column_name: "value_column"
      timestamp_column: "measured_at"
      training_period:
        period: month
        count: 1
      time_bucket:
        period: hour
        count: 12
      detection_delay:
        period: hour
        count: 12
  - elementary.column_anomalies:
      column_anomalies:
        - null_count
        - null_percent
        - zero_count
        - zero_percent
      column_name: "value_column"
      timestamp_column: "measured_at"
      training_period:
        period: month
        count: 1
      time_bucket:
        period: hour
        count: 12
      detection_delay:
        period: hour
        count: 12
      ignore_small_changes:
        spike_failure_percent_threshold: 15
        drop_failure_percent_threshold: 15
```

**Would you be willing to contribute a fix for this issue?**
Not enough knowledge
