### ISSUE TITLE
DBT Columns for source contains only column that have a description

### ISSUE THREAD

**Issue by olivierdet** [elementary-data/elementary#1668]
**Describe the bug**
DBT columns for source only contains column that have a documentation

**To Reproduce**
1 - Define tables inside sources 
2 - Create 2 columns, one with description the other without 
Only the column with description will appear in dbt_columns

We have something like 
```yml
version: 2

sources:
    tables:
      - name: customer
        columns:
          - name: email
            description: Professional email
          - name: first_name
            meta:
              database_tags:
                data_classification: "level_2"
```

Email appear in dbt_columns, `first_name` not

**Expected behavior**

I would expect to have the 2 columns. 

**Environment (please complete the following information):**

- Elementary CLI (edr) version: 0.16.1
- Elementary dbt package version: 0.16.0
- dbt version you're using 1.8.5
- Data warehouse Snowflake, drivers 1.8.3

**Would you be willing to contribute a fix for this issue?**
Yes, I can help if needed, just don't know where it is located
