### ISSUE TITLE
All anomaly checks failing after upgrading to 0.16.0

### ISSUE THREAD

**Issue by henriklaurentz** [elementary-data/elementary#1671]
**Describe the bug**
All our anomaly checks are raising `column "metric_type" does not exist in data_monitoring_metrics`  during `dbt test` after upgrading to dbt 0.16.0.

**To Reproduce**

1.Apply some "model level" tests
```
    data_tests:
      - elementary.table_anomalies:
          tags: ["elementary"]
          severity: warn
      - elementary.dimension_anomalies:
          tags: ["elementary"]
          severity: warn
          dimensions:
            - tool
      - elementary.all_columns_anomalies:
          tags: ["elementary"]
          severity: warn

```
2. Run `dbt test`
3. Receive errors along the lines of:
```
[2024-08-13, 10:28:03 UTC] {pod_manager.py:447} INFO - [base]   Database Error in test elementary_all_columns_anomalies_slv_events_document_analytics_ (models/silver/events/production/events.yml)
[2024-08-13, 10:28:03 UTC] {pod_manager.py:447} INFO - [base]   column "metric_type" does not exist in data_monitoring_metrics
```

**Expected behavior**
That the anomaly tests runs simply successfully, as on former versions.

**Screenshots**
The columns in `data_monitoring_metrics`, closest to `metric_type` being `metric_name`

![image](https://github.com/user-attachments/assets/411119f4-a0e1-463b-bc08-6d625cc9f3e3)

**Environment (please complete the following information):**

- Elementary CLI (edr) version: Irrelevant
- Elementary dbt package version: 0.16.0
- dbt version you're using: 1.8.3
- Data warehouse: Redshift
- Infrastructure details: "Production" nightly `dbt run` + `dbt test` ran from Airflow in k8s pod.

**Additional context**
To clarify, `dbt deps` + `dbt run -s elementary --vars` has been ran before running `dbt test` on version `0.16.0`

**Would you be willing to contribute a fix for this issue?**
Not sure if that would be the most pragmatic approach :)
