### ISSUE TITLE
Make source freshness test descriptions configurable

### ISSUE THREAD

**Issue by waligob** [elementary-data/elementary#1901]
**Is your feature request related to a problem? Please describe.**
It appears that the test description for source freshness tests is a [hard-coded string](https://github.com/elementary-data/dbt-data-reliability/blob/1517d9df8954be91f2c4b2eb6cc835647f029622/macros/edr/dbt_artifacts/upload_dbt_sources.sql#L90).

**Describe the solution you'd like**
 It would be helpful if this could be made configurable via a property under the `meta` block.

**Describe alternatives you've considered**
As a workaround, we're appending metadata to `sources[].tables[].description`, but that requires navigating from the test results to Elementary's lineage graph, and then selecting "..." > "Node info" in order to view that metadata 

**Additional context**

![Image](https://github.com/user-attachments/assets/b477246a-75d9-427f-bde1-28d8c6245aa1)

**Would you be willing to contribute this feature?**
Yes!

_This issue is duplicated from https://github.com/elementary-data/dbt-data-reliability/issues/807_

**Comment by NoyaOffer** [comment]
Hey @waligob ! 🙂 
This string is the default in case there's no customized description.
Try adding this:
```
  - elementary.freshness_anomalies:
          meta:
              description: "Your own test description"
```

Let me know if this helps.

**Comment by waligob** [comment]
@NoyaOffer Given the following freshness test configuration, where would your snippet go if I wanted to override the default description?

```yml
sources:
  - name: auth0
    loader: Stitch
    tables:
      - name: auth0_export
        description: >
          This table contains an export of our auth0 database.
          auth0 is used for user authentication and is our source for registered users
        loaded_at_field: _sdc_batched_at
        freshness:
          error_after:
            count: 28
            period: hour
```

**Comment by skmtyuu** [comment]
This still reproduces on the current implementation.

  The source freshness description appears to still be hard-coded here:
  https://github.com/elementary-data/elementary/blob/v0.23.1/dbt-data-reliability/macros/edr/dbt_artifacts/upload_dbt_sources.sql#L89-L90

  Because of that, it does not seem that `description` can currently be overridden for source freshness alerts in the same way it can for regular dbt tests.

  Also, based on the current behavior, the suggestion in the previous comment to use:

  ```yml
  - elementary.freshness_anomalies:
      meta:
        description: "Your own test description"
```

  does not seem to apply to dbt source freshness alerts. That may work for Elementary freshness anomaly tests, but not for dbt source freshness results.

  So unless I am missing another supported configuration path, this looks like an unresolved product gap rather than a user configuration issue.
Could this issue be reopened?
