### ISSUE TITLE
Threshold-based anomaly alerting

### ISSUE THREAD

**Issue by milhtp** [elementary-data/elementary#1933]
**Is your feature request related to a problem? Please describe.**
In anomaly detection, it would be helpful to have a configuration available where anomaly alerts are only triggered if the metric value exceeds a specific threshold. For example, I might want to detect anomalies in row counts but only alert if the count is over 20 (to reduce noise from small fluctuations in low-volume tables).

**Describe the solution you'd like**
Optional config that allows you to set upper / lower thresholds. When set, values will only be flagged as anomalies when they cross those thresholds within the detection period, AND have a significant anomaly_score.

```
        data_tests:
          - elementary.column_anomalies:
              upper_anomaly_threshold: 20
              lower_anomaly_threshold: 5
```

**Describe alternatives you've considered**
where_expression applies to the whole model, not just the detection period

**Would you be willing to contribute this feature?**
No
