### ISSUE TITLE
[ELE-125] Allowing test configuration on different level

### ISSUE THREAD

**Issue by henriklaurentz** [elementary-data/elementary#329]
Hi, here is a request to improve running test on a models with varying size. This was originally posted in the support channel on Slack [here](https://elementary-community.slack.com/archives/C02CTC89LAX/p1664175230800859) which is also the reason why the copy-pasted description below looks more like a question than a request.

---

I have a question regarding test configuration. Its stated here that there are three levels of configuration available for anomaly tests but I miss information about which type of configuration is available and where exactly it should go.
For example; We have a model with a large output and for this we want to configure days_back: 14 rather than the global days_back: 90 which we have defined as default in the dbt_project.yml vars.
I have not been successful in this and would like to get some help. Below is a example .sql to help clarify:
```
models:
  - name: MODEL_WITH_LARGE_OUTPUT
    description: ~
    config:
      days_back: 14 # <--- This doesn't seem to be picked up by elementary
      meta:
        owner: ~
        days_back: 14 # <--- This doesn't seem to be picked up by elementary
      tags: []
      elementary:
        timestamp_column: ts
        days_back: 14 # <--- This doesn't seem to be picked up by elementary
    tests:
      - elementary.table_anomalies:
          days_back: 14 # <--- The macros doesn't support this argument so this is a no go.
          tags: ["elementary"]
```
So, how should I go about having model specific configuration that should override the global value?
Thanks in advance!

<sub>[ELE-125](https://linear.app/elementary/issue/ELE-125/allowing-test-configuration-on-different-level)</sub>
