### ISSUE TITLE
Better logging and error tracing for GCS Client 

### ISSUE THREAD

**Issue by seanglynn-thrive** [elementary-data/elementary#330]
My team and I are currently facing an issue where our `edr monitor send-report` is failing while attempting to upload our elementary report to a GCS bucket. 

For context, we are executing the `edr monitor send-report` command from the **elementary-data/run-elementary-action@v1** GH Action.

```yml
      - name: Run Elementary CI
        uses: elementary-data/run-elementary-action@v1
        with:
          warehouse-type: ${{ env.WAREHOUSE_TYPE }} # Type of warehouse to use (bigquery, snowflake, redshift, etc.)
          profiles-yml: ${{ secrets.ELEMENTARY_CI_PROFILES_YML }} # Content of ~/.dbt/profiles.yml, should have an `elementary` profile.
          bigquery-keyfile: ${{ secrets.OUR_JSON_KEYFILE }} # If using BigQuery, the content of its keyfile.
          gcs-keyfile: ${{ secrets.OUR_JSON_KEYFILE }} # If using BigQuery, the content of its keyfile.
          # Read from the test results table, generate the Elementary UI and send it to GCS:
          edr-command: |
            edr monitor --slack-token ${{ secrets.SLACK_TOKEN }} --slack-channel-name ${{ secrets.SLACK_CHANNEL_NAME }}
            edr monitor send-report --slack-token ${{ secrets.SLACK_TOKEN }} \
              --slack-channel-name ${{ secrets.SLACK_CHANNEL_NAME }} \
              --google-service-account-path /tmp/gcs_keyfile.json \
              --gcs-bucket-name gs://our-report-bucket \
              --update-bucket-website false
              #--gcs-bucket-name our-report-bucket
              # --bucket-file-path data-team/PR_${{ env.GH_PR_NUMBER }}_report.html

```

Note: We have tried to pass different variations of the GCS related parameters (i.e. different prefixes and paths) but still we're getting the same exception at the end of each action.

The error message that we receive is not very helpful and does not give us a lot of information to find the source of the issue: 

```log
2022-09-27 12:56:18,218 — elementary.clients.gcs.client — ERROR — Failed to upload report to GCS.
```

After digging into the code, I noticed that there is not a lot of logging in the GCS Client class:
https://github.com/elementary-data/elementary/blob/1a85cb8da955d99c78a50e044d92f229c11bc2b9/elementary/clients/gcs/client.py#L26-L38

We would like to add more verbose logging here to allow for more granular error traces.

I have opened a PR to add more verbose logging to the GCS Client class:
https://github.com/elementary-data/elementary/pull/331
