### ISSUE TITLE
On-end-run hook failing after updating package version

### ISSUE THREAD

**Issue by mc51** [elementary-data/elementary#375]
When running dbt test, I'm getting this error message:

```
12:36:04  Running 1 on-run-end hook
12:36:12  Elementary: Uploaded dbt artifacts successfully.
12:36:15  Elementary: Uploaded run results successfully.
12:36:19  Elementary: Handled test results successfully.
12:36:19  Database error while running on-run-end
12:36:19  Encountered an error:
Database Error
  value too long for type character varying(16384)
```

Here's the log file:

```
insert into "devdb"."my_schema_elementary"."dbt_invocations"(invocation_id,run_started_at,run_completed_at,generated_at,command,dbt_version,elementary_version,full_refresh,vars,selected_resources) values
    ('a1b44140-36b4-431a-b1a4-58c59506c2ed','2022-11-02 12:35:45','2022-11-02 12:36:19','2022-11-02 12:36:19','test','1.3.0','0.5.4',False,'{}','[ "a list with many elements" ]')
  
[0m12:36:19.363328 [debug] [MainThread]: Postgres adapter: Postgres error: value too long for type character varying(16384)

```

**To Reproduce**
Can't currently pin it down exactly. But I upgraded from dbt 1.2.1 and elementary 0.4.11 to dbt 1.3.0 and elementary 0.5.4. So maybe, elementary created the schema using `character varying(16384)` before and now tries to insert something longer than that (its 16643 characters).

**Expected behavior**
No error.

**Environment (please complete the following information):**

edr:
```
Name: elementary-data
Version: 0.5.4
```

dbt:
```
Core:
  - installed: 1.3.0
  - latest:    1.3.0 - Up to date!

Plugins:
  - postgres: 1.3.0 - Up to date!
  - redshift: 1.3.0 - Up to date!
```

my dbt  `packages.yml`:

```
packages:
  - package: dbt-labs/codegen # Auto create schemas and models
    version: 0.8.1
  - package: elementary-data/elementary
    version: 0.5.4
  - package: dbt-labs/dbt_utils
    version: 0.9.2

```
