### ISSUE TITLE
[ELE-180] Multiple alerts channels

### ISSUE THREAD

**Issue by Deathfireofdoom** [elementary-data/elementary#572]
**Is your feature request related to a problem? Please describe.**
Today it is only possible to specify one specific channel for a Slack-alert. This could be troublesome if there is multiple stakeholders. 

Also, even if there is only one stakeholder outside the "data-team", the ability to both notify outside-stakeholders and the internal Data-team would be valuable. The stakeholders could have a lower threshold on "alert-noice". 

**Describe the solution you'd like**
I see two different solutions on this.

_Solution 1_
A simple solution letting the user specify multiple slack-channels in the `alerts_config`.

```
models:
  - name: marketing_leads
    columns:
      - name: column_name
        tests:
          - unique:
              meta:
                alerts_config:
                  channel: 
                     - marketing_data_ops
                     - general_data_ops 
```

_Solution 2_ 
A more complex solution making it possible to specify different `alerts_config`. This solution would allow to give different context/information depending on the consumer of the message. The idea behind this solution is that a data-ops person may want/need more information about an error in order to troubleshoot it, while a stakeholder only needs to know that something is wrong and how to act. 

Ex.
```
models:
  - name: marketing_leads
    columns:
      - name: column_name
        tests:
          - unique:
              meta:
                - alerts_config: #config 1
                   channel: 
                      - marketing_data_ops
                   description: "The marketing-dashboard may show inconsistent information, the 
                                          data ops team has been notified."
                - alerts_config: #config 2 
                   channel: 
                      - general_data_ops
                   description: "{test_name} constraint on {column_name} in model {model_name} has 
                                          been breached."                           
```

**Describe alternatives you've considered**
Alternatives could be to use the tags, adding the channel in error message so they get alerted. 

**Additional context**
-

**Would you be willing to contribute this feature?**
Yeah, if you need help I would more than happily look into it. 

<sub>[ELE-180](https://linear.app/elementary/issue/ELE-180/multiple-alerts-channels)</sub>
