### ISSUE TITLE
[ELE-208] Add gitlab guide to documentation 

### ISSUE THREAD

**Issue by clad** [elementary-data/elementary#599]
As a new user of elementary, I would like some documentation on adding elementary to gitlab ci.  If nothing else, a sample gitlab-ci.yml would help gitlab users. I think the safe assumption would be that the user already has a working gitlab ci/cd setup with dbt, and wants to add elementary to it.

<sub>[ELE-208](https://linear.app/elementary/issue/ELE-208/add-gitlab-guide-to-documentation)</sub>

**Comment by elongl** [comment]
Hi @clad! By a little help from the GitLab docs,
I was able to get a good starting point for what `.gitlab-ci.yml` should look like,
however, I did not test it myself at the moment.

Here's the file (make sure to replace `<ADAPTER>`):
```yml
stages:
  - monitor

elementary:
  stage: monitor
  script:
    - apt-get update -qy && apt-get install -y python-dev python-pip # This might not be required.
    - mkdir -p ~/.dbt && echo "$PROFILES_YML" > ~/.dbt/profiles.yml
    - pip install elementary-data[<ADAPTER>]
    - edr monitor --slack-webhook $SLACK_WEBHOOK
```

You'll need to create two variables in **Settings > CI/CD > Variables** in your GitLab project:

* `PROFILES_YML` - The content of your `profiles.yml` file.
* `SLACK_WEBHOOK` - Your Slack webhook.

Please let me know what you think.
Thanks a lot.

**Comment by clad** [comment]
@elongl This looks good to me, thanks!

**Comment by elongl** [comment]
@clad Just to make sure I understand, did you try it and it worked properly?

**Comment by esenilsson** [comment]
@elongl Hi, may I ask what image is used for the stage? ubuntu or your docker image

**Comment by clad** [comment]
@elongl - This sample works, minor edits needed for ubuntu image.

```yml
image: ubuntu:latest

stages:
  - monitor

elementary:
  stage: monitor
  script:
    - apt-get update -qy && apt-get install -y python3-dev python3-pip
    - mkdir ~/.dbt
    - pip install elementary-data[snowflake]
    - edr monitor
```

**Comment by elongl** [comment]
@esenilsson @clad 
That's actually a great point!
I think it'd be much better to utilize the official Docker image.

Could you try the following `.gitlab-ci.yml` and share how it turned out?
```yaml
image:
  name: ghcr.io/elementary-data/elementary:latest
  entrypoint: [""]

stages:
  - monitor

elementary:
  stage: monitor
  script:
    - mkdir -p ~/.dbt && echo "$PROFILES_YML" > ~/.dbt/profiles.yml
    - edr monitor --slack-webhook $SLACK_WEBHOOK
```

Thanks a lot.
