### ISSUE TITLE
[ELE-35] Tests configuration changes

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#65]
The key for choosing specific tests today has the same name as the test.
We got feedback that this is confusing and inconsistent between tests. 

```
# Current format:

        - elementary.all_columns_anomalies:
            all_columns_anomalies:
              - null_count

# Suggested format:

        - elementary.all_columns_anomalies:
            monitors:
              - null_count

```

Also - we should accept the param 'all' as another option to activate all the monitors, as this is more intuitive than all by default. 

<sub>[ELE-35](https://linear.app/elementary/issue/ELE-35/tests-configuration-changes)</sub>
