### ISSUE TITLE
[ELE-533] Alert Suppression on test not suppressing

### ISSUE THREAD

**Issue by RoiTabach** [elementary-data/elementary#759]
**Describe the bug**
When setting up an alert_suppression on a test , after getting one alert, before the suppression interval passes, another alert is sent.

**To Reproduce**
1. create a yaml config for the test as in appendix
2. run dbt and trigger a test failure
3. run edr - first alert gets sent
4. before suppression interval passed, run dbt and fail the test again, and run edr
6. See alert sent

**Expected behavior**
alert should have been suppressed

**Additional context**
raised in support https://elementary-community.slack.com/archives/C02CTC89LAX/p1678899661417579 
example schema.yml file provided by user in slack (notice the model has multiple tests and only one is supposed to be suppressed) 
```yaml
version: 2

models:
  - name: users
    description: >
      bla
    tests:
      - elementary.volume_anomalies:
          tags: [ 'elementary' ]
          meta:
            description: "Monitor table row count"
          config:
            severity: warn
      - elementary.volume_anomalies:
          timestamp_column: 'signup_timestamp'
          meta:
            description: "Monitor number of signups based on signup date"
            alerts_config:
              alert_suppression_interval: 24
          tags: ['elementary']
          where_expression: "signup_timestamp is not null"
    columns:
      - name: blended_user_id
```

<sub>[ELE-533](https://linear.app/elementary/issue/ELE-533/alert-suppression-on-test-not-suppressing)</sub>
