### ISSUE TITLE
Failure to Exctract subscribers crashing edr monitor

### ISSUE THREAD

**Issue by RoiTabach** [elementary-data/elementary#770]
**Describe the bug**
Raised in support https://elementary-community.slack.com/archives/C02CTC89LAX/p1678867969051109 by user Muthu.

**To Reproduce**
alert config from user:
```yaml
meta:
  alerts_config:
    alert_fields: [ "description", "owners", "tags", "subscribers" ]
    description: "To validate duplicate column in the table /view"
    tags: {target.name}
    owners: "@BI Team"
    subscribers: "BI"
```
have this on a failling test and then run edr monitor that's supposed to notify on the failure

**Expected behavior**
not crashing
