### ISSUE TITLE
Bad indentation when using elementary.generate_schema_baseline_test

### ISSUE THREAD

**Issue by Luttik** [elementary-data/elementary#810]
**Describe the bug**
The output of `dbt run-operation elementary.generate_schema_baseline_test` has bad indentation.

Currently, the resulting data is structured as:

```yaml
Generating schema changes from baseline test for source 'mytable':

sources:
  - name: the_schema
    tables:
  - name: mytable
    columns:
        - ... 
```

While it should be formatted as 

```yaml
Generating schema changes from baseline test for source 'mytable':

sources:
  - name: myschema
    tables:
      - name: mytable
        columns:
          - ...
```

Additionally, there are two very usefull nice to have's for this call:
1. Output in lowercase: It is very common to describe all fields and data-types exclusively in lowercase, the output of the command, however, is currently always fully-uppercase. A flag to change this would be great
2. Automatically add it to existing `.yml` files. It would be fairly doable to scan the existing yml files for the correct sources and appen the tests and column definitions to them for even more ease of use.

**Environment:**
 - edr Version: 0.7.7
 - dbt package Version: 0.7.5
